name: Release
on:
  push:
    tags:
    - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: GridLayout.spoon.zip
          exclusions: '*.git*'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "GridLayout.spoon.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
